message: "ยง4>ยงc Utilisable dans {temps}s."

sticks:

  gunpowder:
    effects:
      - ["speed", 15, 1, true]
      - ["resistance", 20, 2, true]
    cooldown: 30

  diamond:
    effects:
      - [ "slowness", 15, 1, true ]
      - [ "strength", 20, 2, true ]
    cooldown: 10
